language: python
python:
  - "3.6"

cache:
  directories:
    - pip_download_cache

before_install:
  - mkdir -p $PIP_DOWNLOAD_CACHE

install:
  - pip install tox
  - pip install -e .

script:
  - tox -e $TOX_ENV

env:
  global:
    - PIP_DOWNLOAD_CACHE="pip_download_cache"
  matrix:
    - TOX_ENV=py27-django1.8
    - TOX_ENV=py27-django1.11
    - TOX_ENV=py36-django1.8
    - TOX_ENV=py36-django1.11
    - TOX_ENV=py36-django2.0

notifications:
  email: false